name: Terraform Plan & Apply

on:
  push:
    branches:
      - 'dev'
      - 'staging'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      WORKING_DIR: ./deployments

    steps:
      - uses: actions/checkout@v3

      - name: Terraform init
        run: terraform init -backend-config="backend-config.tfvars"
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.${{ github.ref_name }}.tfvars"
        working-directory: ${{ env.WORKING_DIR }}

      - name: Conditional Terraform Apply
        if: github.ref_name == 'dev' || github.ref_name == 'staging'
        run: terraform apply -auto-approve -var-file="terraform.${{ github.ref_name }}.tfvars"
        working-directory: ${{ env.WORKING_DIR }}
