name: Terraform Validate

on:
  pull_request:
    branches: [ "dev" ]
    paths:
      - '**/*.tf'

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      WORKING_DIR: ./deployments
  
    steps:
      - uses: actions/checkout@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ env.WORKING_DIR }}
