name: Validate Infrastructure

on:
  push:
    branches-ignore:
      - 'main'
    paths:
      - 'deployments/main.tf'
  pull_request:
    branches:
      - 'dev'
      - 'staging'
      - 'prod'

jobs:
  terraform:
    name: 'Validate'
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      WORKING_DIR: ./deployments

    steps:
      - uses: actions/checkout@v4

      - name: Terraform init
        id: init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}

      - name: Terraform validate
        id: validate
        run: terraform validate
        working-directory: ${{ env.WORKING_DIR }}
